import { Theme, Translation, Language, CardData } from './types';

export const INITIAL_DATA: CardData = {
  fullName: 'Alex Drajin',
  companyCity: 'Dragon Tech Ltd.',
  welcomeMessage: 'Forging the future with code and fire.',
  photoUrl: 'https://picsum.photos/200/200',
  backgroundImageUrl: '',
  layout: 'single',
  showQrCode: true,
  links: [
    { id: '1', type: 'phone', label: 'Call Me', value: '+123456789' },
    { id: '2', type: 'email', label: 'Email', value: 'alex@dragon.tech' },
    { id: '3', type: 'website', label: 'Portfolio', value: 'www.dragon.tech' },
  ],
};

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: 'CardGenius Pro',
    subtitle: 'Create your digital identity',
    fullName: 'Full Name',
    cityCompany: 'City / Company',
    welcomeText: 'Welcome Message',
    photoUrl: 'Photo URL',
    layout: 'Layout',
    singleColumn: 'Single Column',
    doubleColumn: 'Two Columns',
    links: 'Quick Links',
    addLink: 'Add New Link',
    theme: 'Choose Style',
    downloadImage: 'Download Image',
    downloadPdf: 'Download PDF',
    preview: 'Preview',
    editor: 'Editor',
    selectLanguage: 'Language',
    uploadPhoto: 'Profile Image',
    backgroundImage: 'Background Image',
    uploadBackground: 'Upload Background',
    showQrCode: 'Show QR Code',
    downloadVCard: 'Save Contact (vCard)',
  },
  pt: {
    title: 'CardGenius Pro',
    subtitle: 'Crie sua identidade digital',
    fullName: 'Nome Completo',
    cityCompany: 'Cidade / Empresa',
    welcomeText: 'Mensagem de Boas-vindas',
    photoUrl: 'URL da Foto',
    layout: 'Layout',
    singleColumn: 'Coluna Única',
    doubleColumn: 'Duas Colunas',
    links: 'Links Rápidos',
    addLink: 'Adicionar Link',
    theme: 'Escolher Estilo',
    downloadImage: 'Baixar Imagem',
    downloadPdf: 'Baixar PDF',
    preview: 'Visualizar',
    editor: 'Editor',
    selectLanguage: 'Idioma',
    uploadPhoto: 'Imagem de Perfil',
    backgroundImage: 'Imagem de Fundo',
    uploadBackground: 'Carregar Fundo',
    showQrCode: 'Mostrar QR Code',
    downloadVCard: 'Salvar Contato (vCard)',
  },
  fr: {
    title: 'CardGenius Pro',
    subtitle: 'Créez votre identité numérique',
    fullName: 'Nom Complet',
    cityCompany: 'Ville / Entreprise',
    welcomeText: 'Message de Bienvenue',
    photoUrl: 'URL Photo',
    layout: 'Mise en page',
    singleColumn: 'Colonne Unique',
    doubleColumn: 'Deux Colonnes',
    links: 'Liens Rapides',
    addLink: 'Ajouter un Lien',
    theme: 'Choisir le Style',
    downloadImage: 'Télécharger Image',
    downloadPdf: 'Télécharger PDF',
    preview: 'Aperçu',
    editor: 'Éditeur',
    selectLanguage: 'Langue',
    uploadPhoto: 'Image de Profil',
    backgroundImage: 'Image d\'arrière-plan',
    uploadBackground: 'Télécharger le fond',
    showQrCode: 'Afficher le QR Code',
    downloadVCard: 'Enregistrer le contact',
  },
  es: {
    title: 'CardGenius Pro',
    subtitle: 'Crea tu identidad digital',
    fullName: 'Nombre Completo',
    cityCompany: 'Ciudad / Empresa',
    welcomeText: 'Mensaje de Bienvenida',
    photoUrl: 'URL de Foto',
    layout: 'Diseño',
    singleColumn: 'Una Columna',
    doubleColumn: 'Dos Columnas',
    links: 'Enlaces Rápidos',
    addLink: 'Añadir Enlace',
    theme: 'Elegir Estilo',
    downloadImage: 'Descargar Imagen',
    downloadPdf: 'Descargar PDF',
    preview: 'Vista Previa',
    editor: 'Editor',
    selectLanguage: 'Idioma',
    uploadPhoto: 'Imagen de Perfil',
    backgroundImage: 'Imagen de Fondo',
    uploadBackground: 'Subir Fondo',
    showQrCode: 'Mostrar Código QR',
    downloadVCard: 'Guardar Contacto',
  }
};

export const THEMES: Theme[] = [
  // 13 Temas Originais
  {
    id: 'modern',
    name: 'Modern',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900',
    cardClasses: 'bg-slate-800/50 backdrop-blur-sm border border-slate-700 rounded-lg',
    textClasses: 'text-white',
    accentTextClasses: 'text-purple-400',
    buttonClasses: 'bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-purple-400',
    specialEffect: 'none'
  },
  {
    id: 'dark-neon',
    name: 'Dark Neon',
    category: 'futuristic',
    containerClasses: 'bg-gradient-to-br from-slate-950 via-purple-950 to-slate-950',
    cardClasses: 'bg-slate-900/70 backdrop-blur-md border border-purple-600/30 rounded-lg',
    textClasses: 'text-purple-50',
    accentTextClasses: 'text-purple-400',
    buttonClasses: 'bg-gradient-to-r from-purple-700 to-pink-600 hover:from-purple-800 hover:to-pink-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-purple-400',
    specialEffect: 'neon'
  },
  {
    id: 'fire-dragon',
    name: 'Fire Dragon',
    category: 'fantasy',
    containerClasses: 'bg-gradient-to-br from-orange-950 via-red-900 to-yellow-900',
    cardClasses: 'bg-orange-900/40 backdrop-blur-sm border border-orange-600/50 rounded-lg',
    textClasses: 'text-orange-50',
    accentTextClasses: 'text-orange-400',
    buttonClasses: 'bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-700 hover:to-red-700 text-white',
    fontFamily: 'font-medieval',
    iconColor: 'text-orange-400',
    specialEffect: 'fire'
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-blue-950 via-cyan-900 to-teal-900',
    cardClasses: 'bg-blue-900/40 backdrop-blur-sm border border-cyan-500/40 rounded-lg',
    textClasses: 'text-cyan-50',
    accentTextClasses: 'text-cyan-400',
    buttonClasses: 'bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-cyan-400',
    specialEffect: 'none'
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-green-950 via-emerald-900 to-teal-900',
    cardClasses: 'bg-green-900/40 backdrop-blur-sm border border-emerald-600/40 rounded-lg',
    textClasses: 'text-emerald-50',
    accentTextClasses: 'text-emerald-400',
    buttonClasses: 'bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-emerald-400',
    specialEffect: 'none'
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-orange-900 via-pink-800 to-purple-900',
    cardClasses: 'bg-orange-800/40 backdrop-blur-sm border border-pink-500/40 rounded-lg',
    textClasses: 'text-orange-50',
    accentTextClasses: 'text-pink-400',
    buttonClasses: 'bg-gradient-to-r from-pink-600 to-orange-600 hover:from-pink-700 hover:to-orange-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-pink-400',
    specialEffect: 'none'
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    category: 'futuristic',
    containerClasses: 'bg-gradient-to-br from-slate-950 via-purple-950 to-pink-950',
    cardClasses: 'bg-slate-900/80 backdrop-blur-lg border-2 border-pink-600/60 rounded-lg',
    textClasses: 'text-pink-100',
    accentTextClasses: 'text-cyan-400',
    buttonClasses: 'bg-gradient-to-r from-pink-600 to-cyan-600 hover:from-pink-700 hover:to-cyan-700 text-white',
    fontFamily: 'font-futuristic',
    iconColor: 'text-cyan-400',
    specialEffect: 'neon'
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-gray-100 to-gray-200',
    cardClasses: 'bg-white/80 backdrop-blur-sm border border-gray-300/60 rounded-lg',
    textClasses: 'text-gray-900',
    accentTextClasses: 'text-gray-700',
    buttonClasses: 'bg-gradient-to-r from-gray-800 to-gray-600 hover:from-gray-900 hover:to-gray-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-gray-800',
    specialEffect: 'none'
  },
  {
    id: 'aurora-glow',
    name: 'Aurora Glow',
    category: 'fantasy',
    containerClasses: 'bg-gradient-to-br from-purple-900 via-blue-900 to-green-900',
    cardClasses: 'bg-blue-900/50 backdrop-blur-md border border-cyan-400/40 rounded-lg',
    textClasses: 'text-blue-50',
    accentTextClasses: 'text-green-400',
    buttonClasses: 'bg-gradient-to-r from-green-500 to-blue-500 hover:from-green-600 hover:to-blue-600 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-green-400',
    specialEffect: 'glow'
  },
  {
    id: 'gold-luxury',
    name: 'Gold Luxury',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-gray-900 via-amber-950 to-gray-950',
    cardClasses: 'bg-gray-900/60 backdrop-blur-sm border border-amber-600/50 rounded-lg',
    textClasses: 'text-amber-50',
    accentTextClasses: 'text-amber-400',
    buttonClasses: 'bg-gradient-to-r from-amber-600 to-yellow-500 hover:from-amber-700 hover:to-yellow-600 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-amber-400',
    specialEffect: 'none'
  },
  {
    id: 'red-velvet',
    name: 'Red Velvet',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-red-950 via-purple-950 to-slate-950',
    cardClasses: 'bg-red-950/50 backdrop-blur-sm border border-rose-600/50 rounded-lg',
    textClasses: 'text-rose-50',
    accentTextClasses: 'text-rose-400',
    buttonClasses: 'bg-gradient-to-r from-rose-700 to-red-600 hover:from-rose-800 hover:to-red-700 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-rose-400',
    specialEffect: 'none'
  },
  {
    id: 'vivid-neon',
    name: 'Vivid Neon',
    category: 'futuristic',
    containerClasses: 'bg-gradient-to-br from-slate-950 via-fuchsia-950 to-slate-950',
    cardClasses: 'bg-slate-900/60 backdrop-blur-lg border-2 border-lime-400/50 rounded-lg',
    textClasses: 'text-lime-50',
    accentTextClasses: 'text-lime-400',
    buttonClasses: 'bg-gradient-to-r from-fuchsia-600 to-lime-500 hover:from-fuchsia-700 hover:to-lime-600 text-white',
    fontFamily: 'font-futuristic',
    iconColor: 'text-lime-400',
    specialEffect: 'neon'
  },
  {
    id: 'ice-mint',
    name: 'Ice Mint',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-slate-800 via-cyan-900 to-teal-900',
    cardClasses: 'bg-cyan-900/30 backdrop-blur-md border border-teal-400/40 rounded-lg',
    textClasses: 'text-cyan-50',
    accentTextClasses: 'text-cyan-300',
    buttonClasses: 'bg-gradient-to-r from-cyan-500 to-teal-500 hover:from-cyan-600 hover:to-teal-600 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-cyan-300',
    specialEffect: 'none'
  },
  
  // 10 Novos Temas
  {
    id: 'tropical-sunset',
    name: 'Tropical Sunset',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-pink-900 via-orange-800 to-yellow-900',
    cardClasses: 'bg-pink-900/40 backdrop-blur-sm border border-orange-500/40 rounded-lg',
    textClasses: 'text-orange-50',
    accentTextClasses: 'text-yellow-400',
    buttonClasses: 'bg-gradient-to-r from-pink-600 to-yellow-500 hover:from-pink-700 hover:to-yellow-600 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-yellow-400',
    specialEffect: 'none'
  },
  {
    id: 'arctic-blue',
    name: 'Arctic Blue',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-blue-900 via-indigo-950 to-slate-900',
    cardClasses: 'bg-blue-900/50 backdrop-blur-md border border-indigo-500/30 rounded-lg',
    textClasses: 'text-indigo-50',
    accentTextClasses: 'text-indigo-400',
    buttonClasses: 'bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-700 hover:to-blue-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-indigo-400',
    specialEffect: 'none'
  },
  {
    id: 'mystic-purple',
    name: 'Mystic Purple',
    category: 'fantasy',
    containerClasses: 'bg-gradient-to-br from-purple-950 via-violet-900 to-purple-900',
    cardClasses: 'bg-purple-900/50 backdrop-blur-lg border border-violet-500/40 rounded-lg',
    textClasses: 'text-violet-50',
    accentTextClasses: 'text-violet-400',
    buttonClasses: 'bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-700 hover:to-purple-700 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-violet-400',
    specialEffect: 'glow'
  },
  {
    id: 'emerald-premium',
    name: 'Emerald Premium',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-emerald-950 via-green-900 to-slate-900',
    cardClasses: 'bg-emerald-900/50 backdrop-blur-sm border border-emerald-500/40 rounded-lg',
    textClasses: 'text-emerald-50',
    accentTextClasses: 'text-emerald-400',
    buttonClasses: 'bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-emerald-400',
    specialEffect: 'none'
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-rose-900 via-pink-800 to-orange-900',
    cardClasses: 'bg-rose-900/40 backdrop-blur-sm border border-pink-500/40 rounded-lg',
    textClasses: 'text-rose-50',
    accentTextClasses: 'text-rose-400',
    buttonClasses: 'bg-gradient-to-r from-rose-600 to-pink-600 hover:from-rose-700 hover:to-pink-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-rose-400',
    specialEffect: 'none'
  },
  {
    id: 'midnight-jazz',
    name: 'Midnight Jazz',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-slate-950 via-blue-950 to-gray-950',
    cardClasses: 'bg-slate-900/60 backdrop-blur-lg border border-slate-700/50 rounded-lg',
    textClasses: 'text-slate-100',
    accentTextClasses: 'text-slate-300',
    buttonClasses: 'bg-gradient-to-r from-slate-800 to-slate-700 hover:from-slate-900 hover:to-slate-800 text-white',
    fontFamily: 'font-elegant',
    iconColor: 'text-slate-300',
    specialEffect: 'none'
  },
  {
    id: 'desert-sand',
    name: 'Desert Sand',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-amber-900 via-yellow-800 to-orange-900',
    cardClasses: 'bg-amber-900/40 backdrop-blur-sm border border-yellow-600/40 rounded-lg',
    textClasses: 'text-amber-50',
    accentTextClasses: 'text-yellow-500',
    buttonClasses: 'bg-gradient-to-r from-yellow-600 to-amber-600 hover:from-yellow-700 hover:to-amber-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-yellow-500',
    specialEffect: 'none'
  },
  {
    id: 'forest-moss',
    name: 'Forest Moss',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-lime-950 via-green-900 to-slate-950',
    cardClasses: 'bg-lime-900/40 backdrop-blur-sm border border-lime-600/40 rounded-lg',
    textClasses: 'text-lime-50',
    accentTextClasses: 'text-lime-400',
    buttonClasses: 'bg-gradient-to-r from-lime-600 to-green-600 hover:from-lime-700 hover:to-green-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-lime-400',
    specialEffect: 'none'
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-blue-950 via-slate-900 to-cyan-950',
    cardClasses: 'bg-blue-900/50 backdrop-blur-md border border-blue-600/40 rounded-lg',
    textClasses: 'text-blue-50',
    accentTextClasses: 'text-blue-400',
    buttonClasses: 'bg-gradient-to-r from-blue-700 to-cyan-600 hover:from-blue-800 hover:to-cyan-700 text-white',
    fontFamily: 'font-modern',
    iconColor: 'text-blue-400',
    specialEffect: 'none'
  },
  {
    id: 'electric-violet',
    name: 'Electric Violet',
    category: 'futuristic',
    containerClasses: 'bg-gradient-to-br from-violet-950 via-fuchsia-900 to-purple-950',
    cardClasses: 'bg-violet-900/50 backdrop-blur-lg border border-fuchsia-500/40 rounded-lg',
    textClasses: 'text-fuchsia-50',
    accentTextClasses: 'text-fuchsia-400',
    buttonClasses: 'bg-gradient-to-r from-fuchsia-600 to-violet-600 hover:from-fuchsia-700 hover:to-violet-700 text-white',
    fontFamily: 'font-futuristic',
    iconColor: 'text-fuchsia-400',
    specialEffect: 'neon'
  },
  
  // 10 Unique Professional Styles - High Contrast & Different Structures
  {
    id: 'corporate-modern',
    name: 'Corporate Modern',
    category: 'modern',
    containerClasses: 'bg-gradient-to-b from-slate-100 to-slate-200',
    cardClasses: 'bg-white border-l-4 border-blue-600 rounded-lg shadow-md',
    textClasses: 'text-slate-900',
    accentTextClasses: 'text-blue-600',
    buttonClasses: 'bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-md shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-blue-600',
    specialEffect: 'none'
  },
  {
    id: 'luxury-minimal',
    name: 'Luxury Minimal',
    category: 'elegant',
    containerClasses: 'bg-white',
    cardClasses: 'bg-white border-2 border-gray-200 rounded-xl shadow-sm',
    textClasses: 'text-gray-900',
    accentTextClasses: 'text-yellow-500',
    buttonClasses: 'bg-yellow-500 hover:bg-yellow-600 text-gray-900 font-bold rounded-lg shadow-md',
    fontFamily: 'font-elegant',
    iconColor: 'text-yellow-500',
    specialEffect: 'none'
  },
  {
    id: 'tech-vibrant',
    name: 'Tech Vibrant',
    category: 'futuristic',
    containerClasses: 'bg-gradient-to-br from-gray-950 via-blue-950 to-gray-950',
    cardClasses: 'bg-gray-900 border-2 border-cyan-400 rounded-lg shadow-lg',
    textClasses: 'text-cyan-100',
    accentTextClasses: 'text-cyan-400',
    buttonClasses: 'bg-cyan-400 hover:bg-cyan-300 text-gray-900 font-bold rounded-lg shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-cyan-400',
    specialEffect: 'none'
  },
  {
    id: 'wellness-nature',
    name: 'Wellness Nature',
    category: 'nature',
    containerClasses: 'bg-gradient-to-br from-emerald-50 via-green-50 to-teal-50',
    cardClasses: 'bg-white/80 border border-emerald-300 rounded-3xl shadow-md',
    textClasses: 'text-emerald-900',
    accentTextClasses: 'text-emerald-600',
    buttonClasses: 'bg-emerald-600 hover:bg-emerald-700 text-white font-semibold rounded-full shadow-md',
    fontFamily: 'font-modern',
    iconColor: 'text-emerald-600',
    specialEffect: 'none'
  },
  {
    id: 'premium-dark',
    name: 'Premium Dark',
    category: 'elegant',
    containerClasses: 'bg-black',
    cardClasses: 'bg-gray-900 border border-gray-800 rounded-xl shadow-2xl',
    textClasses: 'text-gray-100',
    accentTextClasses: 'text-amber-400',
    buttonClasses: 'bg-amber-500 hover:bg-amber-600 text-black font-bold rounded-lg shadow-xl',
    fontFamily: 'font-elegant',
    iconColor: 'text-amber-400',
    specialEffect: 'none'
  },
  {
    id: 'elegant-light',
    name: 'Elegant Light',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-rose-50 to-pink-50',
    cardClasses: 'bg-white rounded-2xl shadow-lg border-t-4 border-rose-400',
    textClasses: 'text-rose-950',
    accentTextClasses: 'text-rose-500',
    buttonClasses: 'bg-rose-500 hover:bg-rose-600 text-white font-bold rounded-lg shadow-md',
    fontFamily: 'font-elegant',
    iconColor: 'text-rose-500',
    specialEffect: 'none'
  },
  {
    id: 'bold-creative',
    name: 'Bold Creative',
    category: 'creative',
    containerClasses: 'bg-gradient-to-br from-purple-600 via-fuchsia-600 to-orange-500',
    cardClasses: 'bg-white rounded-2xl shadow-2xl',
    textClasses: 'text-gray-900',
    accentTextClasses: 'text-purple-700',
    buttonClasses: 'bg-purple-700 hover:bg-purple-800 text-white font-bold rounded-lg shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-purple-700',
    specialEffect: 'none'
  },
  {
    id: 'studio-pro',
    name: 'Studio Professional',
    category: 'modern',
    containerClasses: 'bg-gradient-to-r from-indigo-900 to-slate-900',
    cardClasses: 'bg-slate-800/60 backdrop-blur-sm border-2 border-indigo-400/40 rounded-lg shadow-lg',
    textClasses: 'text-indigo-50',
    accentTextClasses: 'text-indigo-300',
    buttonClasses: 'bg-indigo-500 hover:bg-indigo-600 text-white font-bold rounded-md shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-indigo-300',
    specialEffect: 'none'
  },
  {
    id: 'geo-luxury',
    name: 'Geo Luxury',
    category: 'elegant',
    containerClasses: 'bg-gradient-to-br from-gray-900 via-cyan-900 to-gray-900',
    cardClasses: 'bg-gray-950 rounded-2xl shadow-xl border border-cyan-600/30',
    textClasses: 'text-cyan-100',
    accentTextClasses: 'text-cyan-400',
    buttonClasses: 'bg-cyan-500 hover:bg-cyan-600 text-black font-bold rounded-lg shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-cyan-400',
    specialEffect: 'none'
  },
  {
    id: 'modern-gradient',
    name: 'Modern Gradient',
    category: 'modern',
    containerClasses: 'bg-gradient-to-br from-red-500 via-yellow-400 to-green-500',
    cardClasses: 'bg-white rounded-xl shadow-2xl border border-gray-300',
    textClasses: 'text-gray-900',
    accentTextClasses: 'text-red-600',
    buttonClasses: 'bg-red-600 hover:bg-red-700 text-white font-bold rounded-lg shadow-lg',
    fontFamily: 'font-modern',
    iconColor: 'text-red-600',
    specialEffect: 'none'
  }
];
